apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - main.yaml

  #------- Aplicações -----------

  # # app1
  - ../apps/app1/deployment.yaml

  # # app2
  - ../apps/app2/main.yaml

  # # app3
  - ../apps/app3/main.yaml

  # # app4
  - ../apps/app4/app/main.yaml